---
title: "强权 The Right of the Strongest"
author: "lyd"
date: "2019/11/6"
output:
  tufte::tufte_html: default
ctex: yes
biblio-title: 参考文献
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

[Homepage](http://yuedong.site)

[**文摘**](http://yuedong.site/humanity.html)/- [**康德文集**](http://yuedong.site/humanity/Myessay/kant.html)/- [**契约论-奴隶**](http://yuedong.site/humanity/Contrat/slavery.html)/- [**杂文-贸易摩擦**](http://yuedong.site/humanity/Myessay/tradeconf.html)/- [**杂文-生活法则**](http://yuedong.site/humanity/Myessay/reflectionoflife.html)

***

# 强权 The Right of the Strongest



THE strongest is never strong enough to be always the master,unless he transforms strength into right,and obedience into duty.Hence the right of the strongest,which,though to all seeming meant ironically,is really laid down as a fundamental principle.But are we never to have an explanation of this phrase?

强权的人从来没有使其总是成为主人的能力，除非他将强权合理化，使人们的服从成为职责。因此，强权的合理性，尽管这有点讽刺意味，却总是一件很基本的原则。但难道我们对这种现象无法解释吗？

Force is a physical power,and I fail to see what moral effect it can have.To yield to force is an act of necessity,not of will—at the most,an act of prudence.In what sense can it be a duty?

强迫是一种肉体上的行为，在我看来，它在道德上是站不住脚的。屈服于强权只是被迫而已，并不是发自内心的，其实更多的是一种谨慎。所以屈服怎么可能变成一种职责。

Suppose for a moment that this so-called “right” exists.I maintain that the sole result is a mass of inexplicable nonsense.For,if force creates right,the effect changes with the cause:

就算假设强权的合理性存在，我仍然坚持认为这是荒唐至极的观点。因为，如果强权创造了合理性，那么就有这样的结论：

>every force that is greater than the first succeeds to its right.As soon as it is possible to disobey with impunity,disobedience is legitimate;

>每个更强的强权都可以替代原先强权的合理性，那么就很快的，人们就不会因为不顺从而遭罚，不顺从就成了合法的了。

and,the strongest being always in the right,the only thing that matters is to act so as to become the strongest.But what kind of right is that which perishes when force fails? If we must obey perforce,there is no need to obey because we ought; and if we are not forced to obey,we are under no obligation to do so.Clearly,the word “right” adds nothing to force: in this connection,it means absolutely nothing.

而且，强权总是合理的，那么人们唯一要做的就是是自己成为强权。可随暴力消逝而消逝的合理性又算什么合理呢？如果我们身不由己要遵守什么东西，那就不遵守吧！因为如果我们不是受到强迫，我们是不用遵守强权的。“合理性”不能用在强权身上，因此说强权有合理性的都是狗屁。

>Obey the powers that be.If this means yield to force,it is a good precept,but superfluous:

>服从强权吧。如果这意味着屈于暴力，那就服从，这种想法是个好的箴言，但又多余赘述了。

I can answer for its never being violated.All power comes from God,I admit; but so does all sickness: does that mean that we are forbidden to call in the doctor? A brigand surprises me at the edge of a wood: must I not merely surrender my purse on compulsion; but,even if I could withhold it,am I in conscience bound to give it up? For certainly the pistol he holds is also a power.

我敢说这个想法从未被突破过。我承认所有权利来自于上帝，但所有疾病也是啊，难道你得了病不去找医生吗？假设我在森林遇到强盗，我肯定会被迫交出我的钱包，但是如果我能保住钱包呢？我还会心甘情愿的交出去吗？不过强盗手里有枪而已，那也是一种强权。

>Let us then admit that force does not create right,and that we are obliged to obey only legitimate powers.In that case,my original question recurs.

>所以我们就这么认为吧，强权不能创造合理性，而且我们只甘心服从合法的权威。

这样，我最初的问题又来了？（合法的权威从哪里来？）

（刘越冬 译）