---
title: "Preface to Critique of Pure Reason"
author: "lyd"
date: "2018/8/14"
output:
  tufte::tufte_html: default
ctex: yes
biblio-title: 参考文献
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

[homepage](http://yuedong.site)

[**文摘**](http://yuedong.site/humanity.html)/- [**契约论-强权**](http://yuedong.site/humanity/Contrat/forcepower.html)/- [**契约论-奴隶**](http://yuedong.site/humanity/Contrat/slavery.html)/- [**杂文-贸易摩擦**](http://yuedong.site/humanity/Myessay/tradeconf.html)/- [**杂文-生活法则**](http://yuedong.site/humanity/Myessay/reflectionoflife.html)

***

# 一、纯粹知识与经验知识之区别

 **一切知识始于经验**，原理在于，客观对象作用于人类感官，并且促使人类悟性活动，进而人类悟性将此感性印象**连接**或**离析**，最终形成“关于对象之知识” [@langongwu]。因此在时间上，**凡是我们所拥有的知识，全都始于经验**。

虽然一切知识始于经验，但并非由此得出一切知识从经验产生。由于知识是感官印象与知识能力二者共同作用产生的，因此，当我们获得某知识时，我们不能分辨此知识是来自感官印象还是来自知识能力。试问：日出于东而落于西这一命题是来自感官印象抑或是知识能力呢，想必大多数人回答是感官印象，因为我们每天都能见到太阳的运动，然而单纯感官印象尚不能构成知识，倘若明天太阳突然升于西方，此命题还是正确的吗？Aristototle 在《形而上学》中写道“人类通常使用感觉来认识事物，而在诸多感觉中，视觉最受青睐。”反问之，我们何以知道视觉呈现给我们的便是真的呢？再试问：三角形内角和为360度这一命题是否为真？

 是否有离经验乃至离一切感官印象而独立自存之知识，则为一至少须严密审查之问题。**脱离经验**（或称**先天的**）非指离开某某个别经验，而是指绝对离开一切经验而独立存在的知识，先天的知识由于未杂有经验的知识，因而称之为纯粹的。此处，康德举了一例子：若人将房屋地基挖掉，则房屋将会倒塌。这一命题虽然不用直接经验便能得到，但由于人们已经从其他经验中知道，物体有重量，若其支撑物撤掉便会下坠，因此上述命题并非先天的。另一例子：命题“一切变化皆有原因”也非先天命题，由于**变化**是来自经验的概念。

# 二、论证人们具有某种先天的知识

 现在我们需要一个能辨别先天知识和经验知识的标准了。即如下：
  

1、若一个命题在想到时，可以说它是必然的，那么它就是先天的判断；并且当这一命题并非由其他命题（除了也具有必然性的命题）引出，那么它就是 绝对的先天判断。如上面挖墙脚的例子，判断墙会倒下是先天的，但由于其引子另一命题，故而不是绝对的先天判断。但是，如，物体有重量这一命题，其实并不具有必然性，比如地球突然失去重力，因此严格上讲，判断墙会倒下并非一个先天判断。
`r margin_note("两个命题不可分离，“惟因行使此等标准时，判断之偶然性有时较判断之经验限制更易于显现，或因判断之无限制的普遍性，有时较判断之必然性更易明显证明。” ")`


2、不同于经验的普遍性，绝对先天的判断具有严格的普遍性 [@dengxiaomang]。


 对于纯粹的先天判断，若要从学问中举一个例子，那么数学的所有命题皆可体现，若要从常识中举一个例子，那么可以举“一切变化必有一个原因”这一命题。然而后一命题中仍存在种种问题。本文将在下期详解。



# 三、命题：“一切变化必有一个原因”先天性说明

 康德之前，英国的经验主义到休谟那里发展成怀疑主义，休谟抛弃了因果联系，

>“我们无从得知因果之间的关系，只能得知某些事物总是会连结在一起，而这些事物在过去的经验里又是从不曾分开过的。我们并不能看透连结这些事物背后的理性为何，我们只能观察到这些事物的本身，并且发现这些事物总是透过一种经常的连结而被我们在想像中归类。”
>
> `r tufte::quote_footer('--- David Hume')`

 举个例子，当我们打台球时，白球撞击红球后，红球滚动，一般来讲，我们认为白球撞击红球是原因，红球滚动是结果，但休谟认为我们无法证明何为因果，当我们见过千千万万次台球运动后，我们将白球撞击和红球滚动的感官画面进行连结，然后主观地认为前者是因，后者是果。如此说来，命题“一切变化必有一个原因”是不成立的，因为“变化”是感官经验，我们甚至无法判定“变化”为真，更不必讲其原因是否为真，况且“一切变化必有一个原因”这一命题可能也只是人们思维的主观连结。

 但是康德认为，“原因”这个概念本身就包含了“与结果相连之必然性及规律所有之严格的普遍性之概念”。即现有“变化”和“原因”这两个概念，而后我们才能在经验中对概念进行匹配，如果按休谟的说法，应该用“习惯性联想”替代掉“因果性”，因为这两者是不同的概念，也就是说，因果性是一个先天的概念。但是这个先天的概念何以有必然性和严格的普遍性呢？对这个问题的回答构成了这本书的主要内容，即后面提出的问题，先天的综合判断如何可能？这些先天的判断不依赖于经验，反而，经验倒依赖于这些先天判断。康德写到：

> “盖若经验所依以进行之一切规律，其自身常为经验的，因而为偶然的，则经验有何从得其正确性？盖此等规律固不能视为第一原理者也。”

#  四、先天的知识
`r margin_note("哲学须有一种规定先天的知识之可能性、原理及其范围之学问")`

  当我们有了先天知识的概念后，进一步我们需要一门学问来解释它。先前有大陆学派的笛卡尔提出“我思故我在”，但这一命题的正确性已有后人提出了反驳。对形而上学的研究是离开一切经验领域的，我们的经验无法对这类研究提供任何帮助，因此我们仅能依靠我们的理性。

 数学之所以可以信赖，原因在与我们对数学概念的认知也是来自于经验，试问，若抛去一切感官知觉，我们还能理解平行的含义吗？如“点”、“线”、“面”的概念均由感官获得，因此康德指出，形而上学中的形式逻辑的概念分析不过是重新解释了一个概念，例如我思故我在，或者上帝存在等概念，在我思和上帝这两个概念中已经包含存在的意义了，康德在后面还要讲到分析判断和综合判断，正是对这一点进行说明。柏拉图提出理型论，成为理性主义和独断论的鼻祖，康德写到

>“轻捷之鸽翱翔空中，感遇空气之抗阻，遂悬想在真空中飞行，当更畅适。柏拉图以感官世界限制悟性过甚，遂鼓观念之翼，轻率离感官世界以入纯粹悟性之真空中，其情正同。”

 后来者如笛卡尔、斯宾诺莎、莱布尼茨等都希望通过数学的方法，也即形式逻辑的方法来构建形而上学，他们所用概念超出经验范围之外，因此无法从经验的角度进行反驳，试问，上帝存在这一命题你能反驳吗？就这样他们构建出“完备的形而上学体系”，然而最终在理性的探索中陷入自相矛盾，即康德所讲的二律背反。

# 五、分析判断和综合判断
`r margin_note("理性的一切理论的学问都包含有先天的综合判断而以之为原理")`


  在含有主宾关系的一切判断中，若宾词属于主词，即宾词包含于主词概念中，则此判断称为分析判断；而若宾词在主词概念之外，则称之为综合判断。举个栗子，命题“等边三角形是三角形”属于分析判断，因为宾词三角形包含于等边三角形概念中；而命题“万物皆有引力”则属于综合判断，因为万物概念本身并不具有引力概念。                                      

 一切数学的判断绝无例外皆是综合的。例如：

 多数人都认为7+5=12是用矛盾律自“七与五之和”这个概念中推演出来的，但只要我们仔细思考一下，其实“七与五之和”这个概念中，只含有二数连结为一这个事实，并未提及连结这二数之后为何数；又如两点之间直线最短一命题，两点间直线的直这个概念并不包含短这个概念，因此也是综合的判断，且需要直观的帮助。

 自然科学中包含一般的原理都是先天综合判断，如“在物质界之一切变化中，物质之量仍留存不变”及“在运动的一切传达中，动与反动”两个命题。因为在物质概念中，并不包含永存性，而且这两个概念也仅存于思维中，因此是先天的。

 形而上学皆为先天的综合命题，其任务在于除探究已存在的先天概念外，要扩大关于先天的知识，如世界必须有一个起点这一命题。



# **六、纯粹理性之概要问题**

 先天的综合判断何以可能？

 康德认为，之前的形而上学之所以处于矛盾中，原因在于没有解决这一问题，无论是大陆派的理性主义还是英国的经验主义。为解决以上问题，需解决以下问题：纯粹数学何以可能？纯粹自然科学何以可能？

